# Site settings
title: Portfolio 
description: Hey I am Nikhil.

# User settings
username: Nikhil Singh Thakur
user_description:
user_title: AI Engineer/Machine Learning
email: nikhil.thakur97@gmail.com
X_username: nikhil.thakur97
github_username:  nikhilthakur97

exclude: ['package.json', 'src' , 'node_modules']
